name: "🏷️ PR Scope label"

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Label PR
        uses: actions/labeler@v5
        with:
          configuration-path: .github/pr-scope-labeler.yml
          sync-labels: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
